spring:
  application:
    name: "shell"

  datasource:
    url: jdbc:mysql://localhost:3306/shell
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb+srv://sappy:sappy@cluster0.jpshjbn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: vector_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: text-embedding-004
        chat:
          options:
            model: gemini-2.0-flash-lite

    vectorstore:
      mongodb:
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  shell:
    interactive:
      enabled: true


server:
  port: 8080

logging:
  level:
    org:
      springframework:
        shell: TRACE

        ai:
          chat:
            client:
              advisor: DEBUG
