spring:
  application:
    name: "shell"
  datasource:
    url: jdbc:mysql://localhost:3306/shell
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

  port: 8080
  shell:
    interactive:
      enabled: true
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG


